"""add_position_to_users

Revision ID: 86165b8b5b41
Revises: 2beaec4d67d7
Create Date: 2025-12-06 13:35:48.821367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86165b8b5b41'
down_revision = '2beaec4d67d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
